// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4H6pLmytC_usIAIRWFNa3x9AIijI2yGI',
    appId: '1:352004648887:web:a6240c148e644ba00e4232',
    messagingSenderId: '352004648887',
    projectId: 'easyhome-956de',
    authDomain: 'easyhome-956de.firebaseapp.com',
    storageBucket: 'easyhome-956de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQe1wC9DYUqVl8feRRyrIJpgCt9UixYY',
    appId: '1:352004648887:android:2422628de05a1f2e0e4232',
    messagingSenderId: '352004648887',
    projectId: 'easyhome-956de',
    storageBucket: 'easyhome-956de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDGH9xcfhRLbBA8Esir6quPPcENKoenwI',
    appId: '1:352004648887:ios:5a84b09f2fdcc6e80e4232',
    messagingSenderId: '352004648887',
    projectId: 'easyhome-956de',
    storageBucket: 'easyhome-956de.appspot.com',
    iosBundleId: 'com.example.easyhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDGH9xcfhRLbBA8Esir6quPPcENKoenwI',
    appId: '1:352004648887:ios:2c13db7d5bf7834d0e4232',
    messagingSenderId: '352004648887',
    projectId: 'easyhome-956de',
    storageBucket: 'easyhome-956de.appspot.com',
    iosBundleId: 'com.example.easyhome.RunnerTests',
  );
}
